aug_citation:
    train_eval:
        device_id: 5
        src_ntype: author
        tgt_ntype: paper
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        sample_neg_edges: True
        num_epochs: 200
        
    pagelink:
        device_id: 1
        src_ntype: author
        tgt_ntype: paper
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        alpha: 1.0
        beta: 1.0
        k_core: 3
        num_epochs: 50
ogbn-mag6syn:
    train_eval:
        device_id: 3
        src_ntype: author
        tgt_ntype: institution
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        sample_neg_edges: True
        num_epochs: 200
        
    pagelink:
        device_id: 0
        src_ntype: author
        tgt_ntype: institution
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        alpha: 1.0
        beta: 1.0
        k_core: 3
        num_epochs: 50        
synthetic:
    train_eval:
        device_id: 1
        src_ntype: user
        tgt_ntype: item
        pred_etype: likes
        emb_dim: 64
        hidden_dim: 64
        out_dim: 64
        sample_neg_edges: False
        num_epochs: 100
        
    pagelink:
        device_id: 2
        src_ntype: user
        tgt_ntype: item
        pred_etype: likes
        emb_dim: 64
        hidden_dim: 64
        out_dim: 64
        alpha: 1.0
        beta: 1.0
        k_core: 2
        num_epochs: 20
ohgbn-imdbsyn:
    train_eval:
        device_id: 1
        src_ntype: director
        tgt_ntype: actor
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        sample_neg_edges: True
        num_epochs: 200
        
    pagelink:
        device_id: 1
        src_ntype: director
        tgt_ntype: actor
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        alpha: 1.0
        beta: 1.0
        k_core: 3
        num_epochs: 50
rpddsyn:
    train_eval:
        device_id: 6
        src_ntype: a
        tgt_ntype: f
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        sample_neg_edges: True
        num_epochs: 200
        
    pagelink:
        device_id: 6
        src_ntype: a
        tgt_ntype: f
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        alpha: 1.0
        beta: 1.0
        k_core: 3
        num_epochs: 50
HGBn-ACMsyn:
    train_eval:
        device_id: 3
        src_ntype: author
        tgt_ntype: subject
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        sample_neg_edges: True
        num_epochs: 200
        
    pagelink:
        device_id: 3
        src_ntype: author
        tgt_ntype: subject
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        alpha: 1.0
        beta: 1.0
        k_core: 3
        num_epochs: 50
ohgbn-acmsyn:
    train_eval:
        device_id: 2
        src_ntype: author
        tgt_ntype: paper
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        sample_neg_edges: True
        num_epochs: 200
        
    pagelink:
        device_id: 2
        src_ntype: author
        tgt_ntype: paper
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        alpha: 1.0
        beta: 1.0
        k_core: 3
        num_epochs: 50
HGBn-IMDBsyn:
    train_eval:
        device_id: 3
        src_ntype: director
        tgt_ntype: actor
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        sample_neg_edges: True
        num_epochs: 200
        
    pagelink:
        device_id: 3
        src_ntype: director
        tgt_ntype: actor
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        alpha: 1.0
        beta: 1.0
        k_core: 3
        num_epochs: 50
HGBn-DBLPsyn:
    train_eval:
        device_id: 6
        src_ntype: author
        tgt_ntype: term
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        sample_neg_edges: True
        num_epochs: 200
        
    pagelink:
        device_id: 6
        src_ntype: author
        tgt_ntype: term
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        alpha: 1.0
        beta: 1.0
        k_core: 3
        num_epochs: 50